# Configuración reorganizada por apartados

model:
  name: deit_small
  pretrained: true
  checkpoint_path: ""
  image_size: 224

run:
  mode: "pruning with revive ratio fix"
  lr: 1e-5
  batch_size: 256
  can_tokens_revive: False

pruning:
  prune_ratio: 0.0
  pruning_criterion: C2
  # prune_ratio_list: [196, 196, 196, 137, 137, 137, 96, 96, 96, 67, 67, 67] # Número de tokens restantes por capa (se debe usar un revive_ratio de 0.0)

revival:
  revive_ratio: 0.15
  revival_criterion: C4
  # revive_ratio_list: [196, 196, 196, 137, 137, 137, 96, 96, 96, 67, 67, 67] # Número de tokens a revivir por capa (se debe usar un prune_ratio de 1.0)

dataset:
  name: imagenet1k
  data_dir: /home/Data/datasets/imagenet1k

mixup:
  mixup_alpha: 0.8
  cutmix_alpha: 1.0
  cutmix_minmax: null
  prob: 1.0
  switch_prob: 0.5
  mode: batch
  label_smoothing: 0.1
  num_classes: 1000