# Configuración reorganizada por apartados

model:
  name: deit_small
  pretrained: true
  checkpoint_path: ""
  image_size: 224

run:
  mode: "revival heuristic grid search"
  lr: 1.e-5
  batch_size: 256
  can_tokens_revive: True

pruning:
  prune_ratio: [196,171,149,130,113,98,86,75,65,57,49,43]
  pruning_criterion: C2

revival:
  revive_ratio: [22,20,18,16,15,13,12,11,10,9,8,7]
  revival_criterion: C4

dataset:
  name: imagenet1k
  data_dir: /home/Data/datasets/imagenet1k

mixup:
  mixup_alpha: 0.8
  cutmix_alpha: 1.0
  cutmix_minmax: null
  prob: 1.0
  switch_prob: 0.5
  mode: batch
  label_smoothing: 0.1
  num_classes: 1000